#!/bin/bash


# Rails Aliases
alias ss='script/server'
alias sc='script/console'
alias sg='script/generate'
alias tlog='tail -f log/development.log'


# Git Aliases
alias gpm='git push origin master'
alias gs='git status'
alias gc='git commit -m '


